FROM node:10-alpine as build
WORKDIR /app
COPY .babelrc.js /app
COPY .babelrc.server.js /app/
COPY package.json /app
COPY yarn.lock /app
RUN yarn
COPY src/ /app/src
COPY .eslintrc.js /app
COPY postcss.config.js /app
COPY webpack.config.js /app
ENV NODE_ENV production
ENV SENTRY_RELEASE 1
ENV SENTRY_PROJECT bahnhofsabfahrten
RUN yarn build:client

FROM nginx:alpine
COPY --from=build /app/dist/client /usr/share/nginx/html
COPY docker/abfahrten.conf /etc/nginx/conf.d/default.conf
