FROM node:10-alpine as build
WORKDIR /app
COPY .babelrc.js /app
COPY package.json /app
COPY yarn.lock /app
RUN yarn
COPY app/ /app/app
COPY .eslintrc.js /app
COPY postcss.config.js /app
COPY webpack.config.js /app
ENV NODE_ENV production
RUN yarn build:client

FROM nginx:alpine
COPY --from=build /app/dist/client /usr/share/nginx/html
