env:
  - name: ENVIRONMENT
    value: beta

hostName: beta.bahn.expert
alternativeHostNames:
  - beta.abfahrten.in
  - beta.marudor.de

resources:
  requests:
    memory: '128Mi'
    cpu: '50m'

replicaCount: 1
