export default {
  ver: '1.20',
  lang: 'deu',
  id: 'ssgeuszm6ieby4w8',
  err: 'OK',
  cInfo: { code: 'OK', url: '', msg: '' },
  svcResL: [
    {
      meth: 'LocMatch',
      err: 'OK',
      res: {
        common: {
          locL: [],
          prodL: [
            { name: 'ICE', icoX: 0, cls: 1 },
            { name: 'EC', icoX: 1, cls: 2 },
            { name: 'IC', icoX: 2, cls: 2 },
            { name: 'NJ', icoX: 3, cls: 2 },
            { name: 'BTE', icoX: 4, cls: 4 },
            { name: 'BUS', icoX: 5, cls: 4 },
            { name: 'Bus', icoX: 6, cls: 4 },
            { name: 'D', icoX: 4, cls: 4 },
            { name: 'FLX', icoX: 4, cls: 4 },
            { name: 'MSM', icoX: 4, cls: 4 },
            { name: 'UEX', icoX: 4, cls: 4 },
            {
              name: 'Bus SEV',
              nameS: 'SEV',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SEV' },
            },
            {
              name: 'BusSE900',
              nameS: 'SE900',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE900' },
            },
            {
              name: 'BusSE901',
              nameS: 'SE901',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE901' },
            },
            {
              name: 'BusSE904',
              nameS: 'SE904',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE904' },
            },
            {
              name: 'BusSE909',
              nameS: 'SE909',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE909' },
            },
            {
              name: 'BusSE930',
              nameS: 'SE930',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE930' },
            },
            {
              name: 'BusSE933',
              nameS: 'SE933',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE933' },
            },
            {
              name: 'BusSE937',
              nameS: 'SE937',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE937' },
            },
            {
              name: 'BusSE950',
              nameS: 'SE950',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE950' },
            },
            {
              name: 'BusSE958',
              nameS: 'SE958',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE958' },
            },
            {
              name: 'BusSE964',
              nameS: 'SE964',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE964' },
            },
            {
              name: 'BusSEV61',
              nameS: 'SEV61',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SEV61' },
            },
            {
              name: 'BusSEV71',
              nameS: 'SEV71',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SEV71' },
            },
            { name: 'IRE', icoX: 8, cls: 8 },
            { name: 'ME', icoX: 9, cls: 8 },
            { name: 'NBE', icoX: 9, cls: 8 },
            { name: 'RB', icoX: 10, cls: 8 },
            { name: 'RE', icoX: 9, cls: 8 },
            { name: 'RE', icoX: 11, cls: 8 },
            {
              name: 'S 1',
              nameS: '1',
              icoX: 7,
              cls: 16,
              prodCtx: { lineId: '1' },
            },
            {
              name: 'S 2',
              nameS: '2',
              icoX: 7,
              cls: 16,
              prodCtx: { lineId: '2' },
            },
            {
              name: 'S 3',
              nameS: '3',
              icoX: 7,
              cls: 16,
              prodCtx: { lineId: '3' },
            },
            {
              name: 'S 11',
              nameS: '11',
              icoX: 7,
              cls: 16,
              prodCtx: { lineId: '11' },
            },
            {
              name: 'S 21',
              nameS: '21',
              icoX: 7,
              cls: 16,
              prodCtx: { lineId: '21' },
            },
            {
              name: 'S 31',
              nameS: '31',
              icoX: 7,
              cls: 16,
              prodCtx: { lineId: '31' },
            },
            {
              name: 'Bus 1',
              nameS: '1',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '1' },
            },
            {
              name: 'Bus 2',
              nameS: '2',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '2' },
            },
            {
              name: 'Bus 3',
              nameS: '3',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '3' },
            },
            {
              name: 'Bus 5',
              nameS: '5',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '5' },
            },
            {
              name: 'Bus 6',
              nameS: '6',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '6' },
            },
            {
              name: 'Bus 15',
              nameS: '15',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '15' },
            },
            {
              name: 'Bus 20',
              nameS: '20',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '20' },
            },
            {
              name: 'Bus 25',
              nameS: '25',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '25' },
            },
            {
              name: 'Bus 31',
              nameS: '31',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '31' },
            },
            {
              name: 'Bus 34',
              nameS: '34',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '34' },
            },
            {
              name: 'Bus 35',
              nameS: '35',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '35' },
            },
            {
              name: 'Bus 36',
              nameS: '36',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '36' },
            },
            {
              name: 'Bus 37',
              nameS: '37',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '37' },
            },
            {
              name: 'Bus 109',
              nameS: '109',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '109' },
            },
            {
              name: 'Bus 111',
              nameS: '111',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '111' },
            },
            {
              name: 'Bus 112',
              nameS: '112',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '112' },
            },
            {
              name: 'Bus 120',
              nameS: '120',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '120' },
            },
            {
              name: 'Bus 124',
              nameS: '124',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '124' },
            },
            {
              name: 'Bus 150',
              nameS: '150',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '150' },
            },
            {
              name: 'Bus 183',
              nameS: '183',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '183' },
            },
            {
              name: 'Bus 250',
              nameS: '250',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '250' },
            },
            {
              name: 'Bus 283',
              nameS: '283',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '283' },
            },
            {
              name: 'Bus 288',
              nameS: '288',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '288' },
            },
            {
              name: 'Bus 600',
              nameS: '600',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '600' },
            },
            {
              name: 'Bus 601',
              nameS: '601',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '601' },
            },
            {
              name: 'Bus 606',
              nameS: '606',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '606' },
            },
            {
              name: 'Bus 607',
              nameS: '607',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '607' },
            },
            {
              name: 'Bus 608',
              nameS: '608',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '608' },
            },
            {
              name: 'Bus 609',
              nameS: '609',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '609' },
            },
            {
              name: 'Bus 621',
              nameS: '621',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '621' },
            },
            {
              name: 'Bus 640',
              nameS: '640',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '640' },
            },
            {
              name: 'Bus 688',
              nameS: '688',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '688' },
            },
            {
              name: 'Bus E86',
              nameS: 'E86',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: 'E86' },
            },
            {
              name: 'Bus 6920',
              nameS: '6920',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '6920' },
            },
            {
              name: 'Fäh 61',
              nameS: '61',
              icoX: 7,
              cls: 64,
              prodCtx: { lineId: '61' },
            },
            {
              name: 'Fäh 62',
              nameS: '62',
              icoX: 7,
              cls: 64,
              prodCtx: { lineId: '62' },
            },
            {
              name: 'Fäh 72',
              nameS: '72',
              icoX: 7,
              cls: 64,
              prodCtx: { lineId: '72' },
            },
            {
              name: 'Fäh 73',
              nameS: '73',
              icoX: 7,
              cls: 64,
              prodCtx: { lineId: '73' },
            },
            {
              name: 'Fäh 75',
              nameS: '75',
              icoX: 7,
              cls: 64,
              prodCtx: { lineId: '75' },
            },
            {
              name: 'Fäh68Air',
              nameS: '68Air',
              icoX: 7,
              cls: 64,
              prodCtx: { lineId: '68Air' },
            },
            { name: 'KAT', icoX: 12, cls: 64 },
            {
              name: 'U 1',
              nameS: '1',
              icoX: 7,
              cls: 128,
              prodCtx: { lineId: '1' },
            },
            {
              name: 'U 2',
              nameS: '2',
              icoX: 7,
              cls: 128,
              prodCtx: { lineId: '2' },
            },
            {
              name: 'U 3',
              nameS: '3',
              icoX: 7,
              cls: 128,
              prodCtx: { lineId: '3' },
            },
            {
              name: 'U 4',
              nameS: '4',
              icoX: 7,
              cls: 128,
              prodCtx: { lineId: '4' },
            },
            {
              name: 'BusSE905',
              nameS: 'SE905',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE905' },
            },
            {
              name: 'BusSE944',
              nameS: 'SE944',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE944' },
            },
            {
              name: 'BusSE962',
              nameS: 'SE962',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE962' },
            },
            { name: 'erx', icoX: 9, cls: 8 },
            {
              name: 'Bus 14',
              nameS: '14',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '14' },
            },
            {
              name: 'Bus 141',
              nameS: '141',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '141' },
            },
            {
              name: 'Bus 142',
              nameS: '142',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '142' },
            },
            {
              name: 'Bus 143',
              nameS: '143',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '143' },
            },
            {
              name: 'Bus 144',
              nameS: '144',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '144' },
            },
            {
              name: 'Bus 145',
              nameS: '145',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '145' },
            },
            {
              name: 'Bus 146',
              nameS: '146',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '146' },
            },
            {
              name: 'Bus 148',
              nameS: '148',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '148' },
            },
            {
              name: 'Bus 149',
              nameS: '149',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '149' },
            },
            {
              name: 'Bus 152',
              nameS: '152',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '152' },
            },
            {
              name: 'Bus 153',
              nameS: '153',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '153' },
            },
            {
              name: 'Bus 154',
              nameS: '154',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '154' },
            },
            {
              name: 'Bus 157',
              nameS: '157',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '157' },
            },
            {
              name: 'Bus 241',
              nameS: '241',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '241' },
            },
            {
              name: 'Bus 245',
              nameS: '245',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '245' },
            },
            {
              name: 'Bus 340',
              nameS: '340',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '340' },
            },
            {
              name: 'Bus 345',
              nameS: '345',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '345' },
            },
            {
              name: 'Bus 349',
              nameS: '349',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '349' },
            },
            {
              name: 'Bus 443',
              nameS: '443',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '443' },
            },
            {
              name: 'Bus 543',
              nameS: '543',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '543' },
            },
            {
              name: 'Bus 641',
              nameS: '641',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '641' },
            },
            {
              name: 'Bus 642',
              nameS: '642',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '642' },
            },
            {
              name: 'Bus 643',
              nameS: '643',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '643' },
            },
            {
              name: 'Bus 644',
              nameS: '644',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '644' },
            },
            {
              name: 'Bus 4148',
              nameS: '4148',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '4148' },
            },
            {
              name: 'Bus 4244',
              nameS: '4244',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '4244' },
            },
            { name: 'AKN', icoX: 9, cls: 8 },
            {
              name: 'Bus 4',
              nameS: '4',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '4' },
            },
            {
              name: 'Bus 603',
              nameS: '603',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '603' },
            },
            {
              name: 'Bus 604',
              nameS: '604',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '604' },
            },
            {
              name: 'Bus 605',
              nameS: '605',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '605' },
            },
            {
              name: 'Bus RE1',
              nameS: 'RE1',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'RE1' },
            },
            {
              name: 'BusSE906',
              nameS: 'SE906',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE906' },
            },
            {
              name: 'BusSE939',
              nameS: 'SE939',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE939' },
            },
            {
              name: 'BusSE960',
              nameS: 'SE960',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE960' },
            },
            {
              name: 'Bus 12',
              nameS: '12',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '12' },
            },
            {
              name: 'Bus 135',
              nameS: '135',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '135' },
            },
            {
              name: 'Bus 136',
              nameS: '136',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '136' },
            },
            {
              name: 'Bus 137',
              nameS: '137',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '137' },
            },
            {
              name: 'Bus 221',
              nameS: '221',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '221' },
            },
            {
              name: 'Bus 222',
              nameS: '222',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '222' },
            },
            {
              name: 'Bus 223',
              nameS: '223',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '223' },
            },
            {
              name: 'Bus 225',
              nameS: '225',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '225' },
            },
            {
              name: 'Bus 227',
              nameS: '227',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '227' },
            },
            {
              name: 'Bus 228',
              nameS: '228',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '228' },
            },
            {
              name: 'Bus 232',
              nameS: '232',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '232' },
            },
            {
              name: 'Bus 234',
              nameS: '234',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '234' },
            },
            {
              name: 'Bus 235',
              nameS: '235',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '235' },
            },
            {
              name: 'Bus 327',
              nameS: '327',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '327' },
            },
            {
              name: 'Bus 329',
              nameS: '329',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '329' },
            },
            {
              name: 'Bus 332',
              nameS: '332',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '332' },
            },
            {
              name: 'Bus 534',
              nameS: '534',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '534' },
            },
            {
              name: 'Bus 535',
              nameS: '535',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '535' },
            },
            {
              name: 'Bus 629',
              nameS: '629',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '629' },
            },
            {
              name: 'Bus 649',
              nameS: '649',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '649' },
            },
            {
              name: 'Bus 4400',
              nameS: '4400',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '4400' },
            },
            {
              name: 'Bus 8800',
              nameS: '8800',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '8800' },
            },
            {
              name: 'Bus 8810',
              nameS: '8810',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '8810' },
            },
            {
              name: 'Bus 8890',
              nameS: '8890',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '8890' },
            },
            {
              name: 'Bus E-Sh',
              nameS: 'E-Sh',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: 'E-Sh' },
            },
            {
              name: 'BusSE902',
              nameS: 'SE902',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE902' },
            },
            {
              name: 'BusSE966',
              nameS: 'SE966',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE966' },
            },
            {
              name: 'BusSE968',
              nameS: 'SE968',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE968' },
            },
            {
              name: 'Bus 160',
              nameS: '160',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '160' },
            },
            {
              name: 'Bus 261',
              nameS: '261',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '261' },
            },
            {
              name: 'BusSE938',
              nameS: 'SE938',
              icoX: 7,
              cls: 8,
              prodCtx: { lineId: 'SE938' },
            },
            {
              name: 'Bus 116',
              nameS: '116',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '116' },
            },
            {
              name: 'Bus 230',
              nameS: '230',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '230' },
            },
            {
              name: 'Bus 321',
              nameS: '321',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '321' },
            },
            {
              name: 'Bus 330',
              nameS: '330',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '330' },
            },
            {
              name: 'Bus 529',
              nameS: '529',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '529' },
            },
            {
              name: 'Bus 130',
              nameS: '130',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '130' },
            },
            {
              name: 'Bus 13',
              nameS: '13',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '13' },
            },
            {
              name: 'Bus 151',
              nameS: '151',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '151' },
            },
            {
              name: 'Bus 156',
              nameS: '156',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '156' },
            },
            {
              name: 'Bus 252',
              nameS: '252',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '252' },
            },
            {
              name: 'Bus 351',
              nameS: '351',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '351' },
            },
            {
              name: 'Bus 355',
              nameS: '355',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '355' },
            },
            {
              name: 'Bus 623',
              nameS: '623',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '623' },
            },
            {
              name: 'Bus 181',
              nameS: '181',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '181' },
            },
            {
              name: 'Bus 184',
              nameS: '184',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '184' },
            },
            {
              name: 'Bus 281',
              nameS: '281',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '281' },
            },
            {
              name: 'Bus 284',
              nameS: '284',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '284' },
            },
            {
              name: 'Bus 613',
              nameS: '613',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '613' },
            },
            {
              name: 'Bus 9',
              nameS: '9',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '9' },
            },
            {
              name: 'Bus 24',
              nameS: '24',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '24' },
            },
            {
              name: 'Bus 26',
              nameS: '26',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '26' },
            },
            {
              name: 'Bus 162',
              nameS: '162',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '162' },
            },
            {
              name: 'Bus 164',
              nameS: '164',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '164' },
            },
            {
              name: 'Bus 168',
              nameS: '168',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '168' },
            },
            {
              name: 'Bus 264',
              nameS: '264',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '264' },
            },
            {
              name: 'Bus 275',
              nameS: '275',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '275' },
            },
            {
              name: 'Bus 362',
              nameS: '362',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '362' },
            },
            {
              name: 'Bus 364',
              nameS: '364',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '364' },
            },
            {
              name: 'Bus 368',
              nameS: '368',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '368' },
            },
            {
              name: 'Bus 462',
              nameS: '462',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '462' },
            },
            {
              name: 'Bus 562',
              nameS: '562',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '562' },
            },
            {
              name: 'Bus E62',
              nameS: 'E62',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: 'E62' },
            },
            {
              name: 'Bus 27',
              nameS: '27',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '27' },
            },
            {
              name: 'Bus 167',
              nameS: '167',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '167' },
            },
            {
              name: 'Bus 567',
              nameS: '567',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '567' },
            },
            {
              name: 'Bus 10',
              nameS: '10',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '10' },
            },
            {
              name: 'Bus 263',
              nameS: '263',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '263' },
            },
            {
              name: 'Bus 618',
              nameS: '618',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '618' },
            },
            {
              name: 'Bus 602',
              nameS: '602',
              icoX: 7,
              cls: 32,
              prodCtx: { lineId: '602' },
            },
          ],
          polyL: [],
          layerL: [{ id: 'standard', name: 'standard', index: 0, annoCnt: 0 }],
          crdSysL: [{ id: 'standard', index: 0, type: 'WGS84' }],
          opL: [],
          remL: [],
          icoL: [
            {
              res: 'ICE',
              fg: { r: -1, g: -1, b: -1 },
              bg: { r: -1, g: -1, b: -1 },
            },
            {
              res: 'EC',
              fg: { r: -1, g: -1, b: -1 },
              bg: { r: -1, g: -1, b: -1 },
            },
            {
              res: 'IC',
              fg: { r: -1, g: -1, b: -1 },
              bg: { r: -1, g: -1, b: -1 },
            },
            {
              res: 'NJ',
              fg: { r: -1, g: -1, b: -1 },
              bg: { r: -1, g: -1, b: -1 },
            },
            {
              res: 'DPF',
              fg: { r: -1, g: -1, b: -1 },
              bg: { r: -1, g: -1, b: -1 },
            },
            {
              res: 'BUS',
              fg: { r: -1, g: -1, b: -1 },
              bg: { r: -1, g: -1, b: -1 },
            },
            {
              res: 'Bus',
              fg: { r: -1, g: -1, b: -1 },
              bg: { r: -1, g: -1, b: -1 },
            },
            {
              res: 'prod_gen',
              fg: { r: -1, g: -1, b: -1 },
              bg: { r: -1, g: -1, b: -1 },
            },
            {
              res: 'IRE',
              fg: { r: -1, g: -1, b: -1 },
              bg: { r: -1, g: -1, b: -1 },
            },
            {
              res: 'DPN',
              fg: { r: -1, g: -1, b: -1 },
              bg: { r: -1, g: -1, b: -1 },
            },
            {
              res: 'RB',
              fg: { r: -1, g: -1, b: -1 },
              bg: { r: -1, g: -1, b: -1 },
            },
            {
              res: 'RE',
              fg: { r: -1, g: -1, b: -1 },
              bg: { r: -1, g: -1, b: -1 },
            },
            {
              res: 'KAT',
              fg: { r: -1, g: -1, b: -1 },
              bg: { r: -1, g: -1, b: -1 },
            },
          ],
        },
        match: {
          field: 'S',
          state: 'L',
          locL: [
            {
              lid:
                'A=1@O=HAMBURG@X=9997434@Y=53557110@U=80@L=008096009@B=1@p=1541025646@',
              type: 'S',
              name: 'HAMBURG',
              icoX: 0,
              extId: '008096009',
              state: 'F',
              crd: { x: 9997434, y: 53557110, layerX: 0, crdSysX: 0 },
              meta: true,
              pCls: 255,
              pRefL: [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
                25,
                26,
                27,
                28,
                29,
                30,
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                40,
                41,
                42,
                43,
                44,
                45,
                46,
                47,
                48,
                49,
                50,
                51,
                52,
                53,
                54,
                55,
                56,
                57,
                58,
                59,
                60,
                61,
                62,
                63,
                64,
                65,
                66,
                67,
                68,
                69,
                70,
                71,
                72,
                73,
                74,
                75,
                76,
                77,
                78,
                79,
                80,
              ],
              wt: 32184,
            },
            {
              lid:
                'A=1@O=Hamburg Hbf@X=10006909@Y=53552733@U=80@L=008002549@B=1@p=1541025646@',
              type: 'S',
              name: 'Hamburg Hbf',
              icoX: 0,
              extId: '008002549',
              state: 'F',
              crd: { x: 10006360, y: 53553533, z: 0, layerX: 0, crdSysX: 0 },
              pCls: 191,
              pRefL: [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                8,
                9,
                10,
                11,
                19,
                24,
                25,
                26,
                27,
                28,
                29,
                30,
                31,
                32,
                33,
                34,
                35,
                38,
                39,
                44,
                46,
                47,
                48,
                49,
                52,
                53,
                61,
                63,
                64,
                69,
                77,
                78,
                79,
                80,
              ],
              wt: 31141,
            },
            {
              lid:
                'A=1@O=Hamburg Dammtor@X=9989569@Y=53560751@U=80@L=008002548@B=1@p=1541025646@',
              type: 'S',
              name: 'Hamburg Dammtor',
              icoX: 0,
              extId: '008002548',
              state: 'F',
              crd: { x: 9989533, y: 53560841, z: 0, layerX: 0, crdSysX: 0 },
              pCls: 59,
              pRefL: [
                0,
                1,
                2,
                3,
                111,
                11,
                19,
                26,
                29,
                30,
                31,
                32,
                33,
                34,
                35,
                112,
                39,
                45,
                49,
                113,
                114,
                115,
              ],
              wt: 30199,
            },
          ],
        },
      },
    },
  ],
};
